modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "All rights reserved"

[[mods]]
modId = "enderitemod"
version = "${version}"
displayName = "Enderite Mod"
authors = "Nic4Las, Pitti11, PianoManu"
description = '''
The Enderite Mod adds new armor and tools, which are successors of Netherite tools. Enderite ore can be found in the End and needs to be blown up before it can be mined. You can smelt the ore in a blast furnace to get scraps, which can be craft with diamonds to Enderite Ingots (similar to Netherite). With these ingots you can craft Enderite tools and blocks, which all have the void floating ability.
'''
logoFile = "icon.png"

[[dependencies.enderitemod]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enderitemod]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enderitemod]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.enderitemod]]
modId = "cloth_config"
type = "optional"
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.enderitemod]]
modId = "shulkerboxtooltip"
type = "optional"
versionRange = "[${shulker_box_tooltip_version},)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "enderitemod-common.mixins.json"